module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-dim": "#0e0e0e",
        "outline": "#767575",
        "surface-variant": "#262626",
        "on-surface-variant": "#adaaaa",
        "surface-tint": "#afa2ff",
        "secondary-container": "#006875",
        "on-primary-fixed-variant": "#2a0091",
        "tertiary-fixed": "#ff8cbe",
        "on-secondary-container": "#e8fbff",
        "primary-container": "#a192ff",
        "on-tertiary-container": "#600039",
        "error": "#ff6e84",
        "secondary": "#00e3fd",
        "primary-fixed-dim": "#9481ff",
        "on-tertiary": "#6d0f44",
        "surface-container-lowest": "#000000",
        "inverse-primary": "#5e40e0",
        "on-secondary-fixed-variant": "#005964",
        "background": "#0e0e0e",
        "on-primary-container": "#210077",
        "primary-fixed": "#a192ff",
        "inverse-surface": "#fcf9f8",
        "tertiary-container": "#ff87bc",
        "on-tertiary-fixed-variant": "#6e1045",
        "tertiary-dim": "#ef7aaf",
        "on-background": "#ffffff",
        "on-error": "#490013",
        "error-container": "#a70138",
        "on-secondary-fixed": "#003a42",
        "surface": "#0e0e0e",
        "error-dim": "#d73357",
        "surface-container-low": "#131313",
        "surface-container-high": "#201f1f",
        "outline-variant": "#484847",
        "secondary-dim": "#00d4ec",
        "on-secondary": "#004d57",
        "on-primary-fixed": "#000000",
        "inverse-on-surface": "#565555",
        "on-tertiary-fixed": "#37001f",
        "secondary-fixed": "#26e6ff",
        "secondary-fixed-dim": "#00d7f0",
        "surface-container": "#1a1919",
        "on-surface": "#ffffff",
        "on-primary": "#2c0097",
        "primary-dim": "#7459f7",
        "tertiary": "#ff9ec7",
        "surface-bright": "#2c2c2c",
        "primary": "#afa2ff",
        "surface-container-highest": "#262626",
        "tertiary-fixed-dim": "#f27db1",
        "on-error-container": "#ffb2b9"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
