// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function RevealInFinder(arg1:string):Promise<void>;

export function SaveReportPDF(arg1:string,arg2:string):Promise<string>;
