// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function SaveReportPDF(arg1, arg2) {
  return window['go']['main']['App']['SaveReportPDF'](arg1, arg2);
}
