package http

import (
	"context"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"

	"mammo/apps/core/internal/application/usecase"
)

// PDFHandler exposes GET /api/studies/:id/pdf — returns a ready-to-download
// laudo PDF generated by the GeneratePDF use case.
type PDFHandler struct {
	generatePDF *usecase.GeneratePDF
}

func NewPDFHandler(gen *usecase.GeneratePDF) *PDFHandler {
	return &PDFHandler{generatePDF: gen}
}

func (h *PDFHandler) RegisterRoutes(api *gin.RouterGroup) {
	api.GET("/studies/:id/pdf", h.downloadPDF)
}

func (h *PDFHandler) downloadPDF(c *gin.Context) {
	id := c.Param("id")
	data, err := h.generatePDF.Execute(context.Background(), id)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	filename := fmt.Sprintf("laudo-%s.pdf", id[:8])
	c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="%s"`, filename))
	c.Data(http.StatusOK, "application/pdf", data)
}
