"""Add profile stats and provider cols

Revision ID: 3f56728ad0d4
Revises: b15ce2179f55
Create Date: 2026-02-17 04:44:54.139912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f56728ad0d4'
down_revision = 'b15ce2179f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('apple_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('microsoft_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('github_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('github_id')
        batch_op.drop_column('microsoft_id')
        batch_op.drop_column('apple_id')
        batch_op.drop_column('google_id')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
