# config/data.yaml

# Caminho absoluto para a raiz do dataset processado
path: /Users/francieliocastro/Developer/ICIT/mamografia-bi-rads-ia/data/yolo_dataset

# Pastas relativas ao 'path' acima (o YOLO concatena automaticamente)
train: images/train
val: images/test     # Usando 'test' como validação por enquanto
test: images/test

# Número de classes
nc: 2

# Nomes das classes (0: Calcification, 1: Mass)
names:
  0: Calcification
  1: Mass